### PR TITLE
Rails 4.1 upgrade

### PR DESCRIPTION
**Pull request by jywarren**
@ryzokuken @icarito  -- trying to tackle this here. Any PRs against this one welcome!

These are changes that are not compatible with Rails 3, unlike #1798.

Heavily based on #1160 by @sjones88

### CODE REVIEW

**Comment by jywarren** [comment]
Also can't seem to add `/bin/*`... yet https://stackoverflow.com/questions/18591399/should-i-add-the-rails-4-bin-directory-to-git#18591998

**Comment by jywarren** [comment]
Most of the errors are either:

`ArgumentError: invalid date` (as in, for example, `WikiControllerTest#test_admin_user_should_delete_wiki_page:`)

or:

```ruby
WikiControllerTest#test_admin_user_should_delete_wiki_page:
Authlogic::Session::Activation::NotActivatedError: You must activate the Authlogic::Session::Base.controller with a controller object before creating objects
    test/functional/wiki_controller_test.rb:12:in `teardown'
```

**Comment by jywarren** [comment]
also noting that Dangerbot is not seeing errors correctly because the format has changed.

**Comment by jywarren** [comment]
OK, the fixtures.rb code in ActiveRecord is trying to load `ruser.rb` instead of `user.rb` based on, apparently, a scan of the fixtures folder.

**Comment by jywarren** [comment]
OK, moving on to ones like:

```ruby

ERROR["test_should_get_show_for_root_page", TalkControllerTest, 2.7286774160020286]
 test_should_get_show_for_root_page#TalkControllerTest (2.73s)
ActionView::Template::Error:         ActionView::Template::Error: SQLite3::SQLException: no such column: community_tags.nid: SELECT "term_data".* FROM "term_data"  WHERE (community_tags.nid = 2 AND name LIKE 'style:fancy')
            app/models/node.rb:382:in `has_tag'
            app/views/layouts/application.html.erb:25:in `_app_views_layouts_application_html_erb___1017683525_53195436'
            test/functional/talk_controller_test.rb:6:in `block in <class:TalkControllerTest>'

ERROR["test_should_assign_correct_value_to_graph_comments_on_GET_stats", StatsControllerTest, 4.533888999008923]
 test_should_assign_correct_value_to_graph_comments_on_GET_stats#StatsControllerTest (4.53s)
ActiveRecord::StatementInvalid:         ActiveRecord::StatementInvalid: SQLite3::SQLException: wrong number of arguments to function COUNT(): SELECT COUNT(created, type, status) FROM "node"  WHERE "node"."type" = 'note' AND "node"."status" = 1 AND ("node"."created" BETWEEN 1511142110 AND 1511746910)
            app/controllers/stats_controller.rb:42:in `index'
            test/functional/stats_controller_test.rb:7:in `block in <class:StatsControllerTest>'
```

**Comment by jywarren** [comment]
`311 tests, 411 assertions, 6 failures, 179 errors, 0 skips`

**Comment by jywarren** [comment]
Better now: `311 tests, 652 assertions, 6 failures, 100 errors, 0 skips`

**Comment by jywarren** [comment]
Note this new process for secrets: http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#config-secrets-yml

**Comment by jywarren** [comment]
I'm pushing this to unstable for testing, as the last remaining issues are with Solr!

**Comment by jywarren** [comment]
@icarito, looks like we have to do a different setup for our secrets, how does this work in production mode containers like unstable?

> Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`

**Comment by jywarren** [comment]
Oh, I tried running ` RAILS_ENV=production SOLR_URL=http://solr:8983/solr/default/ docker-compose -f docker-compose-unstable.yml exec web rake test:solr` on unstable and this triggered a reindexing, which I canceled (it would've taken too long). 

Hmm, not sure how to debug these solr errors:

```ruby
[##################################] [92/92] [100.00%] [00:01] [00:00] [53.27/s]/usr/local/bin/ruby -I"lib:test" -I"/usr/local/bundle/gems/rake-10.5.0/lib" "/usr/local/bundle/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/solr/*_test.rb"  /usr/local/bundle/gems/ci_reporter_test_unit-1.0.1/lib/ci/reporter/rake/test_unit_loader.rb
[Coveralls] Using SimpleCov's default settings.
/usr/local/bundle/gems/activerecord-4.1.16/lib/active_record/associations/builder/collection_association.rb:38: warning: already initialized constant TagNodeAssociationExtension
/usr/local/bundle/gems/activerecord-4.1.16/lib/active_record/associations/builder/collection_association.rb:38: warning: previous definition of TagNodeAssociationExtension was here
Started with run options --seed 60657
 FAIL["test_Node.search_for_two_different_key_words_returns_different_results", NodeSearchTest, 0.20476326099998232]
 test_Node.search_for_two_different_key_words_returns_different_results#NodeSearchTest (0.20s)
        Expected false to be truthy.
        test/solr/node_search_test.rb:30:in `block in <class:NodeSearchTest>'
 FAIL["test_should_get_search_test_action", SearchesControllerTest, 2.7980125459999954]
 test_should_get_search_test_action#SearchesControllerTest (2.80s)
        Expected [] to not be equal to [].
        test/solr/searches_controller_test.rb:23:in `block in <class:SearchesControllerTest>'
 FAIL["test_running_TypeaheadService.notes", TypeaheadServiceTest, 2.857186628999955]
 test_running_TypeaheadService.notes#TypeaheadServiceTest (2.86s)
        Expected: 1
          Actual: 2
        test/solr/typeahead_service_test.rb:20:in `block in <class:TypeaheadServiceTest>'
 FAIL["test_running_TypeaheadService.search_all", TypeaheadServiceTest, 2.9072877629999994]
 test_running_TypeaheadService.search_all#TypeaheadServiceTest (2.91s)
        Expected: 0
          Actual: 1
        test/solr/typeahead_service_test.rb:13:in `block in <class:TypeaheadServiceTest>'
  7/7: [===================================] 100% Time: 00:00:02, Time: 00:00:02
```

**Comment by jywarren** [comment]
Whoa, but perhaps Rails 4 is running right now on unstable? Can you confirm @icarito? I checked and the gemfile says yes...

**Comment by jywarren** [comment]
I manually set the secrets.yml just after the build started.

**Comment by jywarren** [comment]
And this doesn't load, so maybe Solr is not running? http://unstable.publiclab.org/searches/test

**Comment by jywarren** [comment]
Nope, unrelated -- `AbstractController::ActionNotFound (The action 'show' could not be found for SearchesController):` -- must be a routes issue related to the new code.

**Comment by jywarren** [comment]
http://unstable.publiclab.org/api/typeahead/all?srchString=precocious doesn't return anything but this could just be due to the partial reindex...

**Comment by jywarren** [comment]
Manually testing `Node.search { fulltext 'blog' }` for example, on unstable, returns results.

**Comment by jywarren** [comment]
I'm trying now to use this to load test fixtures into the test db and open a rails console in test mode:

```
rake db:fixtures:load RAILS_ENV=test && RAILS_ENV=test bundle exec rails c
```

At the end of:

```
RAILS_ENV=production SOLR_URL=http://solr:8983/solr/default/ docker-compose -f docker-compose-unstable.yml exec web rake db:fixtures:load RAILS_ENV=test && RAILS_ENV=test bundle exec rails c
```

Not sure this'll work!

**Comment by jywarren** [comment]
... it didn't, it just hung. This ran, but in production mode: `RAILS_ENV=test SOLR_URL=http://solr:8983/solr/default/ docker-compose -f docker-compose-unstable.yml exec web rails c`

**Comment by jywarren** [comment]
Hmm, honestly @icarito @ryzokuken i'm a bit stuck on this... why wouldn't the solr tests be passing, esp. if I can run the queries in production mode on the console? Any fresh ideas very welcome! We're VERY close on this... all normal tests are passing, for Rails 4.1

**Comment by jywarren** [comment]
Can we look at the solr logs for the test run to see what queries are actually being triggered by the solr tests?

**Comment by icarito** [comment]
Hi,

Congrats on getting all tests related to Rails 4 upgrade running!

I won't be able to check this out this morning but in the afternoon I'll
set aside time to try this and let you know what I find!

The Solr logs are accessible with the command `docker-compose logs solr`.

Regards,

Sebastian

**Comment by jywarren** [comment]
Oh cool, can I put that command in somewhere to get it to run in Travis?

**Comment by jywarren** [comment]
I added it to `.travis.yml` -- let's see!

**Comment by icarito** [comment]
It doesn't appear to have run the `docker-compose logs` command?

**Comment by icarito** [comment]
Oh I see it... line 3206, reading...

**Comment by icarito** [comment]
It's fine, but it's running _before_ the tests are failing. You need to make _Travis_ run it _after the tests_ so that the logs will tell you what queries are reaching it.

**Comment by icarito** [comment]
Results here https://travis-ci.org/icarito/plots2/builds/308787182#L3573 

For instance:
```
solr_1  | 55000 INFO  (qtp1112280004-15) [   x:default] o.a.s.c.S.Request [default] webapp=/solr path=/select params={q=Chicago&defType=edismax&qf=title_text+body_text&fl=*+score&start=0&fq=type:Node&rows=30&wt=json} hits=0 status=0 QTime=1 
```

**Comment by jywarren** [comment]
https://stackoverflow.com/questions/18668185/sunspot-rails-prevent-indexing-on-save

**Comment by jywarren** [comment]
On reindexing a node, its body is then indexed...

**Comment by jywarren** [comment]
It seems we should be reindexing a little later or something? But we do here: https://github.com/jywarren/plots2/blob/9b81fd4996e469e3492b601dfddeae38b059599c/lib/tasks/test.rake#L38

**Comment by jywarren** [comment]
I've introduced a `Sunspot.reindex` command at the top of the solr-specific tests. It'll reindex the 92 records -- let's see how this does, although it's not a good place to actually declare the reindex...

**Comment by jywarren** [comment]
Whoa, on introducing `Sunspot.reindex` to `test/solr/searches_controller_test.rb`, I now see:

`NoMethodError: undefined method `config' for #<Sunspot::Rails::StubSessionProxy:0x0000000003df2e58>`

That means it's not accessing the real Solr container, but using the fake testing one. Hmm, the custom rake task is supposed to resuscitate the real one... How strange.

**Comment by jywarren** [comment]
Oh wait - this is caused by https://github.com/publiclab/plots2/pull/1799/commits/6a950e36ee62ae8e061c543eb557e55022849e4d, where i added another reindex to travis.yml. Removing that.

**Comment by jywarren** [comment]
!!! Rake tasks! It's not re-enabling solr tasks bc Rails 4 handles rake tasks differently! https://stackoverflow.com/questions/37398935/upgrading-rails-3-to-rails-4-rake-tasks-dont-know-how-to-build-task#37440502

**Comment by jywarren** [comment]
http://technology.customink.com/blog/2015/02/08/customizing-rake-tasks-in-rails-41-and-higher/

**Comment by jywarren** [comment]
That's so odd- again, it's showing that in the solr tests, it's only running the Stub. 

Maybe there's an ordering issue we have to deal with in the new Rails 4 rake tasks?

**Comment by jywarren** [comment]
Somehow under the new rake conventions in rails 4, and the rakefile, normal tests aren't being run.

**Comment by jywarren** [comment]
Clue in latest errors: `JSON::ParserError:         JSON::ParserError: 784: unexpected token at 'Solr search service offline'`

Need to look at ordering and how to ensure solr is actually on when this task runs!

**Comment by jywarren** [comment]
:-/ @ryzokuken any ideas? We're very close here.

**Comment by ryzokuken** [comment]
I'll take a look.

**Comment by jywarren** [comment]
I believe it's running on Ruby 2.3, but should work on 2.1 too. Thanks!

**Comment by jywarren** [comment]
Some helpful notes on default Rake tasks in:

* Rails 4.2 here: https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/test_unit/testing.rake
* Rails 4.1 here: https://github.com/rails/rails/blob/4-1-stable/railties/lib/rails/test_unit/testing.rake

**Comment by jywarren** [comment]
Ummmm, i think we did it!!! There's only this last error due to the Dangerfile and Dangerbot not being able to parse the error output!

**Comment by ryzokuken** [comment]
Sounds cool! I'll try giving it a spin.

**Comment by jywarren** [comment]
Adding a rescue around that part of the Dangerfile, with console logging error. But i want to address that separately.

**Comment by jywarren** [comment]
`The command "tail -n +2 -q ./test/reports/TEST*.xml >> output.xml" exited with 1.`

This is based on https://github.com/jywarren/plots2/blob/rails-4/.travis.yml#L22 

```
  - echo -e '<?xml version="1.0" encoding="UTF-8"?>' > output.xml
```

**Comment by jywarren** [comment]
YAYYYYYYYYY @icarito i'm merging this in now and will push to staging.

**Comment by ryzokuken** [comment]
Awesome! How long before it comes to staging?

**Comment by jywarren** [comment]
I just pushed it there. Fingers X and if you can report back here if it works for you, thank you in advance!

it'll show up at http://staging.publiclab.org/

**Comment by jywarren** [comment]
Hmm, @icarito i see `Incomplete response received from application` -- any idea why?

**Comment by jywarren** [comment]
Ah! we need to set `SECRET_KEY_BASE` -- pretty straightforward.

`Your rails_env production don't have required set up,probably missing secret_key_base.`

https://blog.carbonfive.com/2015/03/17/docker-rails-docker-compose-together-in-your-development-workflow/ has guidance. Is this something you could work on?

Thank you!

**Comment by jywarren** [comment]
http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#config-secrets-yml

**Comment by icarito** [comment]
Super! I'm very happy that we are moving forward our stack. It makes my
life so much more enjoyable when we are on supported releases of base
components.

Sure I'll setup the token.

Regards,

Sebastian

**Comment by ryzokuken** [comment]
Great.

**Comment by icarito** [comment]
Okay I setup the environment variable and we're good!
It is still quite slow for me, although the server load is fine.

**Comment by jywarren** [comment]
Great! I'm very happy too!

Does this change our production deployment process at all or do we need to
add environment variables there before publishing?

Thanks!

**Comment by icarito** [comment]
We can simply edit secrets.yml in production and switch to an
environment variable when we upgrade production to containers. Which
makes me think we may have to do the same with other tokens or secrets
we may have in production.

**Comment by jywarren** [comment]
Great, would you like to do the publication this week at our meeting?
Thanks!

**Comment by jywarren** [comment]
This is pretty weird, but some routes got lost in the upgrade (bad job merging by me) but the tests didn't catch it! Hmm... including `tag#gridsEmbed` and one `subscriptions` in these commits:



However, the tests show:

`573 tests, 1699 assertions, 0 failures, 0 errors, 0 skips` ([here](https://travis-ci.org/publiclab/plots2/builds/312707556?utm_source=github_status&utm_medium=notification))

Vs. the last version before this PR:

```
183 tests, 546 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
311 tests, 800 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
74 tests, 214 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
```

That equals

`568 tests, 1560 assertions`

([here](https://travis-ci.org/publiclab/plots2/builds/310300105))

**Comment by jywarren** [comment]
Update -- i think functional tests do not test routes: https://github.com/publiclab/plots2/pull/1841
