### ISSUE TITLE
callouts are not properly parsing, causes problems with email address and hyphen

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#116]
tweak the regex to include spaces!

    stevie[@publiclab](/profile/publiclab).org

**Comment by btbonval** [comment]
as a followup, I ran into a wall getting the code to run locally and that never got resolved, so I can't really get this code in place and test it.

**Comment by btbonval** [comment]
confirmed both problems in my localhost environment with the following comment:
```
email to web@publiclab.org and then email@admin

checking @who-dat as well
```

`@publiclab`, `@admin`, and `@who` were highlighted, when only `@who-dat` should have been highlighted (and it was not).

**Comment by btbonval** [comment]
code from https://github.com/publiclab/plots2/issues/116#issuecomment-68075247 gives the error `class/module name must be CONSTANT (SyntaxError)`.

Looks like its an issue of capitalization?
http://www.landsberger.com/?p=727

Yeah, capitalization of `callouts` to `Callouts` fixed it. There's something I don't normally think about in a programming language... capitalization as syntax and not convention.

**Comment by jywarren** [comment]
it is an idiosyncracy of ruby, indeed.

**Comment by btbonval** [comment]
Now getting: `undefined method `finder' for Callouts:Module`

I thought I set an attribute inside that module, but it seems to think I'm calling a method.

It looks like Modules have their own special syntax:
http://www.ruby-doc.org/core-2.2.0/Module.html

It looks like attributes should be constants (that should be fine in this case), so complete upper case for the attribute names.

It also looks like I have to add an `attr_reader` to grant access to the attribute for reading via a module.

``` ruby
module Callouts
  FINDER = /(^|\W)\@([\w-]+)\W/
  PRETTYLINK = '[@\2](/profile/\2)'
  attr_reader(:FINDER, :PRETTYLINK)
end
```

Nope. didn't help. `undefined method `FINDER' for Callouts:Module`

**Comment by btbonval** [comment]
Figured it out playing in irb. `Callouts.const_get :FINDER`

That syntax is hideous. I wonder if that's normal in Ruby or considered odd. Whatever, it works, it's in.

**Comment by jywarren** [comment]
I guess I don't see constants much in ruby for some reason. I consider the
syntax odd but might also consider the use of a constant here odd for ruby?
I dunno.

**Comment by btbonval** [comment]
`const_get` works in the console.
```
$ rails console
Loading development environment (Rails 3.2.20)
2.1.2 :001 > Callouts.const_get :FINDER
 => /(^|\W)\@([\w-]+)\W/ 
2.1.2 :002 > Callouts.const_get :PRETTYLINK
 => "[@\\2](/profile/\\2)" 
```

Does not work in Rails.
```
syntax error, unexpected tSYMBEG, expecting ')'
...t :FINDER, Callouts.const_get :PRETTYLINK)
```

**Comment by btbonval** [comment]
full line of code:
``` ruby
comment.gsub(Callouts.const_get :FINDER, Callouts.const_get :PRETTYLINK)
```

Both things work individually. Not sure why they fail inside the gsub. Maybe this is one of those problems mixing parens and spaces for function calling.

**Comment by btbonval** [comment]
nope.
```
syntax error, unexpected tSYMBEG, expecting keyword_end
...t :FINDER, Callouts.const_get :PRETTYLINK
```

full line of code attempted:
``` ruby
comment.gsub Callouts.const_get :FINDER, Callouts.const_get :PRETTYLINK
```

**Comment by btbonval** [comment]
full parens worked.
``` ruby
comment.gsub(Callouts.const_get(:FINDER), Callouts.const_get(:PRETTYLINK))
```

I'll keep my comments about this syntactic nonsense to myself.

**Comment by btbonval** [comment]
Alright, the regex has some problems.

```
email to web@publiclab.org and then email@admin

checking@who-datas well
```

* highlighted all of `web@publiclab.org` with a mailto link (good)
* totally left `email@admin` alone (good)
* `@who-dat` was totally highlighted (good)
  * but spacing on either side was removed (bad)

**Comment by btbonval** [comment]
yeah, spacing lost on either side of the callout regardless of hyphen.

**Comment by btbonval** [comment]
adding `\1` helped replace the space in front of the prettylink resolved the front space problem.
``` ruby
PRETTYLINK = '\1[@\2](/profile/\2)'
```

I tried adding `\3` for anything after the match, but it did not add spacing.
``` ruby
PRETTYLINK = '\1[@\2](/profile/\2)\3'
```

I manually added a space.
``` ruby
PRETTYLINK = '\1[@\2](/profile/\2) '
```

but then `hey @bryan, poop` changed to `hey @bryan poop`, losing the comma and replacing it with a space. Not sure where the comma went.

**Comment by btbonval** [comment]
Ah, I'm guessing its the trailing `\W` in the regex which is matched but then dropped. Wrap it in `(\W)` and use `\3`?

``` ruby
module Callouts
  FINDER = /(^|\W)\@([\w-]+)(\W)/
  PRETTYLINK = '\1[@\2](/profile/\2)\3'
end
```

fixed.

this looks good.

**Comment by btbonval** [comment]
a string starting with `@callout text text` works, but a string ending with `text text @callout` does not work.

Guess we want an option to be `\W` or `$`?

solved.

Alright I can't think of any other ways to break this regex.

**Comment by jywarren** [comment]
wow, really? super!!!!!!! can you run tests and we can push it to
production?

**Comment by btbonval** [comment]
tests were run on my local system. Did you need anything past that?

I made a mistake because the notes use HTML while the comments use markdown. I did a quick fix to differentiate HTML vs Markdown printing via two constants.

I haven't updated the production system since we migrated. Same process as before?

**Comment by btbonval** [comment]
Tested initial callout in comment and note, middle callout in comment and note, ending callout in comment and note. Threw in hyphens and took them out. All create links to the profile as desired for comments and notes.

**Comment by jywarren** [comment]
nope, sounds good!

**Comment by jywarren** [comment]
Hmm, I wonder is this callout parse failure related? http://publiclab.org/notes/warren/03-23-2015/public-lab-talk-at-libreplanet-2015-two-public-labs-and-a-call-for-developers#c11392

**Comment by btbonval** [comment]
Strangely, the ruby tester gets a different result where only the first callout is highlighted from the lot.

http://rubular.com/r/rRxlqUSC8Z

I'd say its a new issue, although it is somehow related to the parser regex.

**Comment by btbonval** [comment]
Ah, I copied what was in this ticket, not the final version in the code. Okay the ruby regex tester confirms the behavior.
http://rubular.com/r/Vevai8HVFi

**Comment by ebarry** [comment]
the WebWG is awesome

--

txt only: +1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>
